server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: dev

  datasource:
    url : jdbc:postgresql://163.44.206.213:5432/devnmdb
    username: devnm
    password: devnm123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0

  security:
    jwt:
      secret: 6ee0722956002f69de212acbe4a300fe58477a38e5f5c1c893ac6407e6936e369d4a428193b024a3d5d8a0ef5ae0f247
      expiration: 86400000 # 24 hours

# Tron Configuration
tron:
  api:
    url: https://api.trongrid.io
  network:
    name: nile
    fullHost: https://nile.trongrid.io
    apiKey: ${TRON_API_KEY:bf5a9e49-d910-4283-8a5b-9669d41281b9}

  contracts:
    usdt: TG3XXyExBkPp9nzdajDZsozEu4BkaSJozs  # USDT on Nile testnet

# HD Wallet Configuration
wallet:
  mnemonic:
    seed: ${WALLET_MNEMONIC_SEED:} # Will generate new if empty

  pool:
    initialSize: 1000  # Generate 1000 child wallets on startup
    minThreshold: 200  # Minimum free wallets before generating more
    batchSize: 500     # How many to generate at once when needed

  master:
    minTrxBalance: 100 # Minimum TRX balance required for master wallet

# Logging
logging:
  level:
    com.UsdtWallet.UsdtWallet: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when_authorized
